import "./globals.scss";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { cn } from "@/_core/components/lib/utils";

import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";

import AppToast from "@/_shared/components/app-toast";
import WrapperProvider from "@/_core/providers/wrapper.provider";
import AppLoading from "@/_shared/components/loading/app-loading";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={cn(
          `${geistSans.variable} ${geistMono.variable}`,
          "min-h-screen bg-background font-sans antialiased"
        )}
      >
        <NextIntlClientProvider messages={messages}>
          <WrapperProvider>
            <AppToast />
            <AppLoading />

            {children}
          </WrapperProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
