import "./globals.scss";
import type { Metadata } from "next";
import { cn } from "@/_core/components/lib/utils";
import { NextIntlClientProvider } from "next-intl";
import AppToast from "@/_shared/components/app-toast";
import { Montserrat as FontSans } from "next/font/google";
import { getLocale, getMessages } from "next-intl/server";
import WrapperProvider from "@/_core/providers/wrapper.provider";
import AppLoading from "@/_shared/components/loading/app-loading";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Next boilerplate",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <NextIntlClientProvider messages={messages}>
          <WrapperProvider>
            <AppToast />
            <AppLoading />

            {children}
          </WrapperProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
